import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

export default tseslint.config(
  {
    ignores: [
      'out/**',
      'release/**',
      'node_modules/**',
      // Throwaway repos from `pnpm fixtures` — deliberately messy sample code.
      'fixtures/**',
      // shadcn/ui files are regenerated by the CLI; linting them only creates
      // churn we would have to re-apply on every `shadcn add`.
      'src/renderer/src/components/ui/**'
    ]
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: [
      'src/main/**/*.ts',
      'src/preload/**/*.ts',
      'src/shared/**/*.ts',
      'scripts/**/*.mjs',
      'tests/**/*.{mts,mjs}'
    ],
    languageOptions: {
      globals: globals.node
    }
  },
  {
    files: ['src/renderer/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // Fires on every useVirtualizer() call. It only means the React Compiler
      // would skip that component, and this project does not enable the
      // compiler — so it is noise, not a finding. Revisit if the compiler is
      // turned on.
      'react-hooks/incompatible-library': 'off'
    }
  },
  {
    files: ['tests/**/*.{mts,mjs}'],
    rules: {
      // The suites tally with `cond ? pass++ : fail++`, which reads better in
      // a scoreboard than an if/else and is confined to this directory.
      '@typescript-eslint/no-unused-expressions': 'off'
    }
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ],
      // Empty catch blocks are load-bearing here: git and fs failures are
      // routinely expected (missing stage, absent marker file) and are handled
      // by the return value, not the exception.
      'no-empty': ['error', { allowEmptyCatch: true }]
    }
  }
)
